language: objective-c
osx_image: xcode7
script:
    - xctool -project Unbox.xcodeproj -scheme Unbox-iOS clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    - xctool -project Unbox.xcodeproj -scheme Unbox-watchOS clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    - xctool -project Unbox.xcodeproj -scheme Unbox-OSX clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    - xctool -project Unbox.xcodeproj -scheme UnboxTests clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
